<?php
/**
 * PGApiTransactionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPaymentGateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Payment Gateway API
 *
 * This document describes the Qualpay Payment Gateway API.
 *
 * OpenAPI spec version: 1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPaymentGateway;

/**
 * PGApiTransactionResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PGApiTransactionResponse
/**
 * @package     calderaPayQualpayPaymentGateway
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PGApiTransactionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PGApiTransactionResponse"
     */
    public function testPGApiTransactionResponse()
    {
    }

    /**
     * Test attribute "merchant_advice_code"
     */
    public function testPropertyMerchantAdviceCode()
    {
    }

    /**
     * Test attribute "pg_id"
     */
    public function testPropertyPgId()
    {
    }

    /**
     * Test attribute "rcode"
     */
    public function testPropertyRcode()
    {
    }

    /**
     * Test attribute "rmsg"
     */
    public function testPropertyRmsg()
    {
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "auth_avs_result"
     */
    public function testPropertyAuthAvsResult()
    {
    }

    /**
     * Test attribute "auth_cvv2_result"
     */
    public function testPropertyAuthCvv2Result()
    {
    }

    /**
     * Test attribute "echo_fields"
     */
    public function testPropertyEchoFields()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }
}
