<?php
/**
 * ShippingAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPaymentGateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Payment Gateway API
 *
 * This document describes the Qualpay Payment Gateway API.
 *
 * OpenAPI spec version: 1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPaymentGateway;

/**
 * ShippingAddressTest Class Doc Comment
 *
 * @category    Class */
// * @description ShippingAddress
/**
 * @package     calderaPayQualpayPaymentGateway
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingAddress"
     */
    public function testShippingAddress()
    {
    }

    /**
     * Test attribute "primary"
     */
    public function testPropertyPrimary()
    {
    }

    /**
     * Test attribute "shipping_addr1"
     */
    public function testPropertyShippingAddr1()
    {
    }

    /**
     * Test attribute "shipping_addr2"
     */
    public function testPropertyShippingAddr2()
    {
    }

    /**
     * Test attribute "shipping_city"
     */
    public function testPropertyShippingCity()
    {
    }

    /**
     * Test attribute "shipping_country"
     */
    public function testPropertyShippingCountry()
    {
    }

    /**
     * Test attribute "shipping_country_code"
     */
    public function testPropertyShippingCountryCode()
    {
    }

    /**
     * Test attribute "shipping_firm_name"
     */
    public function testPropertyShippingFirmName()
    {
    }

    /**
     * Test attribute "shipping_first_name"
     */
    public function testPropertyShippingFirstName()
    {
    }

    /**
     * Test attribute "shipping_last_name"
     */
    public function testPropertyShippingLastName()
    {
    }

    /**
     * Test attribute "shipping_state"
     */
    public function testPropertyShippingState()
    {
    }

    /**
     * Test attribute "shipping_zip"
     */
    public function testPropertyShippingZip()
    {
    }

    /**
     * Test attribute "shipping_zip4"
     */
    public function testPropertyShippingZip4()
    {
    }
}
