<?php
/**
 * CheckoutPreferencesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Platform API
 *
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * CheckoutPreferencesTest Class Doc Comment
 *
 * @category    Class */
// * @description CheckoutPreferences
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutPreferencesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckoutPreferences"
     */
    public function testCheckoutPreferences()
    {
    }

    /**
     * Test attribute "success_url"
     */
    public function testPropertySuccessUrl()
    {
    }

    /**
     * Test attribute "failure_url"
     */
    public function testPropertyFailureUrl()
    {
    }

    /**
     * Test attribute "notification_url"
     */
    public function testPropertyNotificationUrl()
    {
    }

    /**
     * Test attribute "allow_partial_payments"
     */
    public function testPropertyAllowPartialPayments()
    {
    }

    /**
     * Test attribute "allow_save_card"
     */
    public function testPropertyAllowSaveCard()
    {
    }

    /**
     * Test attribute "email_receipt"
     */
    public function testPropertyEmailReceipt()
    {
    }

    /**
     * Test attribute "request_type"
     */
    public function testPropertyRequestType()
    {
    }

    /**
     * Test attribute "expire_in_secs"
     */
    public function testPropertyExpireInSecs()
    {
    }
}
