<?php
/**
 * DisputeReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Platform API
 *
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * DisputeReportTest Class Doc Comment
 *
 * @category    Class */
// * @description DisputeReport
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DisputeReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DisputeReport"
     */
    public function testDisputeReport()
    {
    }

    /**
     * Test attribute "rec_id"
     */
    public function testPropertyRecId()
    {
    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "incoming_date"
     */
    public function testPropertyIncomingDate()
    {
    }

    /**
     * Test attribute "dba_name"
     */
    public function testPropertyDbaName()
    {
    }

    /**
     * Test attribute "batch_id"
     */
    public function testPropertyBatchId()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "tran_date"
     */
    public function testPropertyTranDate()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }

    /**
     * Test attribute "amt_dispute"
     */
    public function testPropertyAmtDispute()
    {
    }

    /**
     * Test attribute "tran_currency"
     */
    public function testPropertyTranCurrency()
    {
    }

    /**
     * Test attribute "purchase_id"
     */
    public function testPropertyPurchaseId()
    {
    }

    /**
     * Test attribute "merch_ref_num"
     */
    public function testPropertyMerchRefNum()
    {
    }

    /**
     * Test attribute "pg_id"
     */
    public function testPropertyPgId()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "reason_code"
     */
    public function testPropertyReasonCode()
    {
    }

    /**
     * Test attribute "rec_id_linked"
     */
    public function testPropertyRecIdLinked()
    {
    }

    /**
     * Test attribute "auth_avs_result"
     */
    public function testPropertyAuthAvsResult()
    {
    }

    /**
     * Test attribute "auth_cvv2_result"
     */
    public function testPropertyAuthCvv2Result()
    {
    }

    /**
     * Test attribute "card_number_original"
     */
    public function testPropertyCardNumberOriginal()
    {
    }

    /**
     * Test attribute "date_status_change"
     */
    public function testPropertyDateStatusChange()
    {
    }
}
