<?php
/**
 * GatewayResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Platform API
 *
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * GatewayResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GatewayResponse
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GatewayResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GatewayResponse"
     */
    public function testGatewayResponse()
    {
    }

    /**
     * Test attribute "pg_id"
     */
    public function testPropertyPgId()
    {
    }

    /**
     * Test attribute "rcode"
     */
    public function testPropertyRcode()
    {
    }

    /**
     * Test attribute "rmsg"
     */
    public function testPropertyRmsg()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "tran_time"
     */
    public function testPropertyTranTime()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }

    /**
     * Test attribute "purchase_id"
     */
    public function testPropertyPurchaseId()
    {
    }

    /**
     * Test attribute "cvv2_result"
     */
    public function testPropertyCvv2Result()
    {
    }

    /**
     * Test attribute "avs_result"
     */
    public function testPropertyAvsResult()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "http_status"
     */
    public function testPropertyHttpStatus()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "merch_ref_num"
     */
    public function testPropertyMerchRefNum()
    {
    }

    /**
     * Test attribute "tran_currency"
     */
    public function testPropertyTranCurrency()
    {
    }

    /**
     * Test attribute "dba_name"
     */
    public function testPropertyDbaName()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }
}
