<?php
/**
 * PGApiTransactionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Payment Gateway API
 *
 * This document describes the Qualpay Payment Gateway API.
 *
 * OpenAPI spec version: 1.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * PGApiTransactionRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description PGApiTransactionRequest
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PGApiTransactionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PGApiTransactionRequest"
     */
    public function testPGApiTransactionRequest()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "amt_convenience_fee"
     */
    public function testPropertyAmtConvenienceFee()
    {
    }

    /**
     * Test attribute "amt_fbo"
     */
    public function testPropertyAmtFbo()
    {
    }

    /**
     * Test attribute "amt_tax"
     */
    public function testPropertyAmtTax()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }

    /**
     * Test attribute "amt_tran_fee"
     */
    public function testPropertyAmtTranFee()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "avs_address"
     */
    public function testPropertyAvsAddress()
    {
    }

    /**
     * Test attribute "avs_zip"
     */
    public function testPropertyAvsZip()
    {
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "card_swipe"
     */
    public function testPropertyCardSwipe()
    {
    }

    /**
     * Test attribute "cardholder_name"
     */
    public function testPropertyCardholderName()
    {
    }

    /**
     * Test attribute "cavv_3ds"
     */
    public function testPropertyCavv3ds()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "customer_code"
     */
    public function testPropertyCustomerCode()
    {
    }

    /**
     * Test attribute "customer_email"
     */
    public function testPropertyCustomerEmail()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "cvv2"
     */
    public function testPropertyCvv2()
    {
    }

    /**
     * Test attribute "dba_name"
     */
    public function testPropertyDbaName()
    {
    }

    /**
     * Test attribute "developer_id"
     */
    public function testPropertyDeveloperId()
    {
    }

    /**
     * Test attribute "echo_fields"
     */
    public function testPropertyEchoFields()
    {
    }

    /**
     * Test attribute "email_receipt"
     */
    public function testPropertyEmailReceipt()
    {
    }

    /**
     * Test attribute "exp_date"
     */
    public function testPropertyExpDate()
    {
    }

    /**
     * Test attribute "fbo_id"
     */
    public function testPropertyFboId()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "loc_id"
     */
    public function testPropertyLocId()
    {
    }

    /**
     * Test attribute "mc_ucaf_data"
     */
    public function testPropertyMcUcafData()
    {
    }

    /**
     * Test attribute "mc_ucaf_ind"
     */
    public function testPropertyMcUcafInd()
    {
    }

    /**
     * Test attribute "merch_ref_num"
     */
    public function testPropertyMerchRefNum()
    {
    }

    /**
     * Test attribute "moto_ecomm_ind"
     */
    public function testPropertyMotoEcommInd()
    {
    }

    /**
     * Test attribute "partial_auth"
     */
    public function testPropertyPartialAuth()
    {
    }

    /**
     * Test attribute "pg_id"
     */
    public function testPropertyPgId()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "purchase_id"
     */
    public function testPropertyPurchaseId()
    {
    }

    /**
     * Test attribute "report_data"
     */
    public function testPropertyReportData()
    {
    }

    /**
     * Test attribute "retry_id"
     */
    public function testPropertyRetryId()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "subscription_id"
     */
    public function testPropertySubscriptionId()
    {
    }

    /**
     * Test attribute "tokenize"
     */
    public function testPropertyTokenize()
    {
    }

    /**
     * Test attribute "tran_currency"
     */
    public function testPropertyTranCurrency()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "xid_3ds"
     */
    public function testPropertyXid3ds()
    {
    }

    /**
     * Test attribute "vendor_id"
     */
    public function testPropertyVendorId()
    {
    }
}
