<?php
/**
 * SubscriptionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Platform API
 *
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * SubscriptionRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description SubscriptionRequest
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscriptionRequest"
     */
    public function testSubscriptionRequest()
    {
    }

    /**
     * Test attribute "date_start"
     */
    public function testPropertyDateStart()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "plan_code"
     */
    public function testPropertyPlanCode()
    {
    }

    /**
     * Test attribute "plan_desc"
     */
    public function testPropertyPlanDesc()
    {
    }

    /**
     * Test attribute "plan_frequency"
     */
    public function testPropertyPlanFrequency()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "plan_duration"
     */
    public function testPropertyPlanDuration()
    {
    }

    /**
     * Test attribute "amt_setup"
     */
    public function testPropertyAmtSetup()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "tran_currency"
     */
    public function testPropertyTranCurrency()
    {
    }

    /**
     * Test attribute "use_existing_customer"
     */
    public function testPropertyUseExistingCustomer()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "vendor_id"
     */
    public function testPropertyVendorId()
    {
    }
}
