<?php
/**
 * TransactionReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  calderaPayQualpayPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qualpay Platform API
 *
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace calderaPayQualpayPlatform;

/**
 * TransactionReportTest Class Doc Comment
 *
 * @category    Class */
// * @description TransactionReport
/**
 * @package     calderaPayQualpayPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionReport"
     */
    public function testTransactionReport()
    {
    }

    /**
     * Test attribute "rec_id"
     */
    public function testPropertyRecId()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "batch_date"
     */
    public function testPropertyBatchDate()
    {
    }

    /**
     * Test attribute "dba_name"
     */
    public function testPropertyDbaName()
    {
    }

    /**
     * Test attribute "merch_city_ph"
     */
    public function testPropertyMerchCityPh()
    {
    }

    /**
     * Test attribute "merch_state"
     */
    public function testPropertyMerchState()
    {
    }

    /**
     * Test attribute "merch_zip"
     */
    public function testPropertyMerchZip()
    {
    }

    /**
     * Test attribute "merch_country"
     */
    public function testPropertyMerchCountry()
    {
    }

    /**
     * Test attribute "batch_number"
     */
    public function testPropertyBatchNumber()
    {
    }

    /**
     * Test attribute "batch_id"
     */
    public function testPropertyBatchId()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "auth_date"
     */
    public function testPropertyAuthDate()
    {
    }

    /**
     * Test attribute "tran_date"
     */
    public function testPropertyTranDate()
    {
    }

    /**
     * Test attribute "settle_date"
     */
    public function testPropertySettleDate()
    {
    }

    /**
     * Test attribute "amt_auth"
     */
    public function testPropertyAmtAuth()
    {
    }

    /**
     * Test attribute "amt_tran"
     */
    public function testPropertyAmtTran()
    {
    }

    /**
     * Test attribute "tran_currency"
     */
    public function testPropertyTranCurrency()
    {
    }

    /**
     * Test attribute "reference_number"
     */
    public function testPropertyReferenceNumber()
    {
    }

    /**
     * Test attribute "purchase_id"
     */
    public function testPropertyPurchaseId()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "moto_ecomm_ind"
     */
    public function testPropertyMotoEcommInd()
    {
    }

    /**
     * Test attribute "pos_entry_mode"
     */
    public function testPropertyPosEntryMode()
    {
    }

    /**
     * Test attribute "amt_funded"
     */
    public function testPropertyAmtFunded()
    {
    }

    /**
     * Test attribute "funded_currency"
     */
    public function testPropertyFundedCurrency()
    {
    }

    /**
     * Test attribute "pg_id"
     */
    public function testPropertyPgId()
    {
    }

    /**
     * Test attribute "merch_ref_num"
     */
    public function testPropertyMerchRefNum()
    {
    }

    /**
     * Test attribute "acq_reference_number"
     */
    public function testPropertyAcqReferenceNumber()
    {
    }

    /**
     * Test attribute "auth_rrn"
     */
    public function testPropertyAuthRrn()
    {
    }

    /**
     * Test attribute "auth_tran_id"
     */
    public function testPropertyAuthTranId()
    {
    }
}
